spring:
  datasource:
    url: jdbc:oracle:thin:@localhost:1522:XE
    username: library
    password: password
  flyway:
    enabled: ${FLYWAY_ENABLED:true}
    baseline-on-migrate: true
    baseline-version: 0

server:
  port: 8080
  servlet:
    context-path: /library/api/


springdoc:
  swagger-ui:
    enabled: true
  api-docs:
    enabled: true
  packagesToScan: com.example.library.web.controller